# Generated by Django 2.2.5 on 2019-10-02 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191002_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 2, 17, 32, 43, 212588, tzinfo=utc)),
        ),
    ]
