# Generated by Django 2.2.5 on 2019-10-02 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191002_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 2, 21, 34, 47, 787785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='USA', max_length=20),
        ),
    ]
