# Generated by Django 2.2.5 on 2019-11-13 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191113_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 13, 22, 11, 19, 242840, tzinfo=utc)),
        ),
    ]
