# Generated by Django 2.2.5 on 2019-12-03 22:42

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0008_auto_20191113_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10,
                                      validators=[django.core.validators.MaxValueValidator(1000),
                                                  django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 3, 22, 42, 41, 97401, tzinfo=utc)),
        ),
    ]
