# Generated by Django 2.2.5 on 2019-12-05 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0011_auto_20191203_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 20, 2, 28, 905796, tzinfo=utc)),
        ),
    ]
